apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-app
      image: tienhuy1801/my-app:v3

      env:
        - name: DEMO
          value: "Hello"

      ports:
        - name: http
          containerPort: 5000

      livenessProbe:
        httpGet:
          path: /health/live
          port: 5000
        initialDelaySeconds: 3
        periodSeconds: 1
        timeoutSeconds: 1
      readinessProbe:
        httpGet:
          path: /health/ready
          port: 5000
        initialDelaySeconds: 3
        periodSeconds: 1
        timeoutSeconds: 1

      resources:
        limits:
          cpu: 200m
          memory: "200Mi"
        requests:
          cpu: 100m
          memory: "100Mi"
