name: Run pytest and autopep8 on pull request

on:
  pull_request:
    branches: [main]

jobs:
  pretest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest

      - name: Run autopep8
        run: autopep8 . --recursive --aggressive --aggressive --diff --exit-code
